baseURL = 'https://thomasprog.github.io/'
canonifyURLs = true
relativeURLs = true

languageCode = 'en-us'
title = 'Prog A to Z'
theme = 'hugo-theme-relearn'

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON", "SEARCH", "SEARCHPAGE"]

# English is the default language
defaultContentLanguage = "en"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir = true

[Languages]
[Languages.en]
title = "Prog'z"
weight = 1
languageName = "English"

[Languages.fr]
title = "Documentation du thème Hugo Learn"
weight = 2
languageName = "Français"

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub"
identifier = "ds"
url = "https://github.com/ThomasProg/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-circle'></i> itch.io"
url = "https://progz.itch.io/"
weight = 11

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-play'></i> youtube"
url = "https://www.youtube.com/ProgZ/"
weight = 12

disqusShortname = "progz"

[params]
  themeVariant = [ "light-theme", "dark-theme", "neon-theme"]
    mathJaxInitialize = "{ \"chtml\": { \"displayAlign\": \"left\" } }"

disableLandingPageButton = true

[markup]
  [markup.highlight]
    # if `guessSyntax = true`, there will be no unstyled code even if no language
    # was given BUT Mermaid and Math codefences will not work anymore! So this is a
    # mandatory setting for your site if you want to use Math codefences
    guessSyntax = false

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
